name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ RMJ242205 }}
        password: ${{ RIYOMSARKAR }}

    # 3. Build Docker image
    - name: Build Docker image
      run: docker build -t rmj242205/dotnetdockerapp1:latest .

    # 4. Push Docker image
    - name: Push Docker image
      run: docker push rmj242205/dotnetdockerapp1:latestname: .NET Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./DotnetDockerCICDApp

      - name: Build
        run: dotnet build ./DotnetDockerCICDApp --configuration Release --no-restore

      - name: Test
        run: dotnet test ./DotnetDockerCICDApp --no-restore --verbosity normal

      - name: Build Docker image
        run: docker build -t dotnetdockerapp ./DotnetDockerCICDApp