name: .NET Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./DotnetDockerCICDApp

      - name: Build
        run: dotnet build ./DotnetDockerCICDApp --configuration Release --no-restore

      - name: Test
        run: dotnet test ./DotnetDockerCICDApp --no-restore --verbosity normal

      - name: Build Docker image
        run: docker build -t dotnetdockerapp ./DotnetDockerCICDApp